services:
  server:
    env_file:
      - ./env/server.env
      - ./env/db.env
    platform: linux/arm64
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    env_file:
      - ./env/db.env
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - data:/data/db

volumes:
  data: